linters:
  enable-all: true
  disable:
    - bidichk
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - interfacebloat
    - interfacer
    - ireturn
    - lll
    - makezero
    - maligned
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - promlinter
    - scopelint
    - sqlclosecheck
    - tagliatelle
    - tenv
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  # Restrict revive to exported.
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        severity: warning
  gci:
    local-prefixes: github.com/smartxworks/cluster-api-provider-elf
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/apimachinery/pkg/types
        alias: apitypes
      - pkg: k8s.io/client-go/kubernetes/scheme
        alias: cgscheme
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: ctrllog
      - pkg: sigs.k8s.io/controller-runtime/pkg/manager
        alias: ctrlmgr
      - pkg: sigs.k8s.io/controller-runtime/pkg/controller/controllerutil
        alias: ctrlutil
      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: ctrllog
      # CAPI
      - pkg: sigs.k8s.io/cluster-api/api/v1beta1
        alias: clusterv1
      - pkg: sigs.k8s.io/cluster-api/errors
        alias: capierrors
      - pkg: sigs.k8s.io/cluster-api/util
        alias: capiutil
      - pkg: sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1beta1
        alias: bootstrapv1
      - pkg: sigs.k8s.io/cluster-api/controlplane/kubeadm/api/v1beta1
        alias: controlplanev1
      - pkg: sigs.k8s.io/cluster-api/test/e2e
        alias: capie2e
      # CAPE
      - pkg: github.com/smartxworks/cluster-api-provider-elf/api/v1beta1
        alias: infrav1
  staticcheck:
    go: "1.19"
  stylecheck:
    go: "1.19"
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # We are disabling default golangci exclusions because we want to help reviewers to focus on reviewing the most relevant
  # changes in PRs and avoid nitpicking.
  exclude-use-default: false
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
    - "exported: exported (const|function|method|type|var) (.+) should have comment or be unexported"
    - "exported: (func|type) name will be used as (.+) by other packages, and that stutters; consider calling this (.+)"
    - (G104|G107|G404|G505|ST1000)
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
  exclude-rules:
    # Exclude revive's exported for certain packages and code, e.g. tests.
    - linters:
      - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      path: .*test/(e2e).*.go
    - linters:
      - errcheck
      text: Error return value is not checked
      path: _test\.go
    - linters:
      - errcheck
      text: Error return value of (.+) is not checked
      path: _test\.go
    - linters:
      - gosec
      text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
    - linters:
      - godot
      text: "Comment should end in a period"
      path: "(.*)/(v1beta1)/(.*)types.go"
    - linters:
      - errcheck
      text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # Disable unparam "always receives" which might not be really
    # useful when building libraries.
    - linters:
      - unparam
      text: always receives
    - linters:
      - unparam
      text: (.+) - (`t`|`g`) is unused  
    - path: _test\.go
      text: cyclomatic complexity
    # Append should be able to assign to a different var/slice.
    - linters:
      - gocritic
      text: "appendAssign: append result not assigned to the same slice"
    # Dot imports for gomega or ginkgo are allowed
    # within test files.
    - path: _test\.go
      text: should not use dot imports
    - path: (e2e|fake)/.*.go
      text: should not use dot imports
    - path: _test\.go
      text: cyclomatic complexity

run:
  timeout: 10m
  skip-files:
  - "zz_generated.*\\.go$"
  allow-parallel-runners: true
